publish_mode: editorial_workflow
media_folder: "images/post-img/original" # Netlify image files will be stored here, to keep separate
backend:
  name: github
  repo: reyemtm/reyemtm.github.io
  branch: master
collections:
  - name: "slides"
    label: "Presentations"
    folder: "slides"
    create: true
    slug: "{{year}}-{{title}}"
    fields: 
      - {label: "Layout", name:"layout","widget":"hidden",default:"slides"}
      - {label: "Theme", name:"theme","widget":"select",default:"white",options:["white","blood","night"]}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Publish Date", name: "date", widget: "datetime"}
      - {label: "Subtitle", name:"subtitle", widget:"string"}
      - {label: "Description",name:"description",widget:"string"}
      - {label: "Netlify Image", name: "netlify-img", widget: "image"}
      - {label: "Featured Image", name: "feature-img", widget: "string"}
      - {label: "Tags", name: "tags", "widget": "list"}
      - {label: "Body", name: "body", widget: "markdown"}
  - name: "blog" # Used in routes
    label: "Blog" # Used in the UI
    folder: "_posts/" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}" # Filename template, e.g., YYYY-MM-DD-title.md
    fields: # The fields for each document, usually in front matter
      - {label: "Layout", name: "layout", widget: "hidden", default: "post"}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Publish Date", name: "date", widget: "datetime"}
      - {label: "Subtitle", name:"subtitle", widget:"string"}
      - {label: "Description",name:"description",widget:"string"}
      - {label: "Netlify Image", name: "netlify-img", widget: "image"}
      - {label: "Featured Image", name: "feature-img", widget: "string"}
      - {label: "Tags", name: "tags", "widget": "list"}
      - {label: "Body", name: "body", widget: "markdown"}
